
const autoridadesOpciones = [
        { id: 1, nombre: "Jefe Policía", valor: "Jefe Policía" },
        { id: 2, nombre: "Subjefe", valor: "Subjefe" },
        { id: 3, nombre: "S.U.E.D.", valor: "S.U.E.D." },
        { id: 4, nombre: "Dirección General Investigaciones Complejas", valor: "Dirección General Investigaciones Complejas" },
        { id: 5, nombre: "Dirección Policía de Investigaciones", valor: "Dirección Policía de Investigaciones" },
        { id: 6, nombre: "Jefe Dpto Investigaciones Complejas", valor: "Jefe Dpto Investigaciones Complejas" },
        { id: 7, nombre: "Dirección Gral. Seguridad Metropolitana", valor: "Dirección Gral. Seguridad Metropolitana" },
        { id: 8, nombre: "Director de Operación Metropolitana", valor: "Director de Operación Metropolitana" },
        { id: 9, nombre: "Director del C.E.A.C.", valor: "Director del C.E.A.C." },
        { id: 10, nombre: "Fiscalía Investigación Penal en Turno", valor: "Fiscalía Investigación Penal en Turno" },
        { id: 11, nombre: "Fiscalía Investigación Penal Nro 1", valor: "Fiscalía Investigación Penal Nro 1" },
        { id: 12, nombre: "Fiscalía Investigación Penal Nro 2", valor: "Fiscalía Investigación Penal Nro 2" },
        { id: 13, nombre: "Fiscalía Investigación Penal Nro 3", valor: "Fiscalía Investigación Penal Nro 3" },
        { id: 14, nombre: "Fiscalía Investigación Penal Nro 4", valor: "Fiscalía Investigación Penal Nro 4" },
        { id: 15, nombre: "Fiscalía Investigación Penal Nro 5", valor: "Fiscalía Investigación Penal Nro 5" },
        { id: 16, nombre: "Fiscalía Investigación Penal Nro 6", valor: "Fiscalía Investigación Penal Nro 6" },
        { id: 17, nombre: "Fiscalía Investigación Penal Nro 7", valor: "Fiscalía Investigación Penal Nro 7" },
        { id: 18, nombre: "Fiscalía Investigación Penal Nro 8", valor: "Fiscalía Investigación Penal Nro 8" },
        { id: 19, nombre: "Fiscalía Investigación Penal Nro 9", valor: "Fiscalía Investigación Penal Nro 9" },
        { id: 20, nombre: "Fiscalía Investigación Penal Nro 10", valor: "Fiscalía Investigación Penal Nro 10" },
        { id: 21, nombre: "Fiscalía Investigación Penal Nro 11", valor: "Fiscalía Investigación Penal Nro 11" },
        { id: 22, nombre: "Fiscalía Investigación Penal Nro 12", valor: "Fiscalía Investigación Penal Nro 12" },
        { id: 23, nombre: "Fiscalía Investigación Penal Nro 13", valor: "Fiscalía Investigación Penal Nro 13" },
        { id: 24, nombre: "Fiscalía Investigación Penal Nro 14", valor: "Fiscalía Investigación Penal Nro 14" },
        { id: 25, nombre: "Fiscalía Investigación Penal Nro 15", valor: "Fiscalía Investigación Penal Nro 15" },
        { id: 26, nombre: "Juzgado del Menor de Edad y la Familia Nro 1", valor: "Juzgado del Menor de Edad y la Familia Nro 1" },
        { id: 27, nombre: "Juzgado del Menor de Edad y la Familia Nro 2", valor: "Juzgado del Menor de Edad y la Familia Nro 2" },
        { id: 28, nombre: "Juzgado del Menor de Edad y la Familia Nro 3", valor: "Juzgado del Menor de Edad y la Familia Nro 3" },
        { id: 29, nombre: "Juzgado del Menor de Edad y la Familia Nro 4", valor: "Juzgado del Menor de Edad y la Familia Nro 4" },
        { id: 30, nombre: "Juzgado del Menor de Edad y la Familia Nro 5", valor: "Juzgado del Menor de Edad y la Familia Nro 5" },
        { id: 31, nombre: "Juzgado del Menor de Edad y la Familia Nro 6", valor: "Juzgado del Menor de Edad y la Familia Nro 6" },
        { id: 32, nombre: "Supervisión Zona I Metropolitana", valor: "Supervisión Zona I Metropolitana" },
        { id: 33, nombre: "Supervisión Zona II Metropolitana", valor: "Supervisión Zona II Metropolitana" },
        { id: 34, nombre: "Supervisión Zona III Metropolitana", valor: "Supervisión Zona III Metropolitana" },
        { id: 35, nombre: "Supervisión Zona IV Metropolitana", valor: "Supervisión Zona IV Metropolitana" },
        { id: 36, nombre: "Supervisión Zona V Metropolitana", valor: "Supervisión Zona V Metropolitana" },
        { id: 37, nombre: "Supervisión Zona VI Metropolitana", valor: "Supervisión Zona VI Metropolitana" },
        { id: 38, nombre: "Supervisión Zona XXII Metropolitana", valor: "Supervisión Zona XXII Metropolitana" },
        { id: 39, nombre: "Expte. y Archivo Dependencia", valor: "Expte. y Archivo Dependencia" }

    ];


export default autoridadesOpciones;