export const jerarquiaCampos = [
    { nombre: "Civil", value: "Civil" },
    { nombre: "Agente", value: "Agente" },
    { nombre: "Cabo", value: "Cabo" },
    { nombre: "Cabo Primero", value: "Cabo Primero" },
    { nombre: "Sargento", value: "Sargento" },
    { nombre: "Sargento Primero", value: "Sargento Primero" },
    { nombre: "Sargento Ayudante", value: "Sargento Ayudante" },
    { nombre: "Suboficial Principal", value: "Suboficial Principal" },
    { nombre: "Suboficial Mayor", value: "Suboficial Mayor" },
    { nombre: "Oficial Subayudante", value: "Oficial Subayudante" },
    { nombre: "Oficial Ayudante", value: "Oficial Ayudante" },
    { nombre: "Oficial Auxiliar", value: "Oficial Auxiliar" },
    { nombre: "Oficial Principal", value: "Oficial Principal" },
    { nombre: "Subcomisario", value: "Subcomisario" },
    { nombre: "Comisario", value: "Comisario" },
    { nombre: "Comisario Principal", value: "Comisario Principal" },
    { nombre: "Comisario Inspector", value: "Comisario Inspector" },
    { nombre: "Comisario Mayor", value: "Comisario Mayor" },
    { nombre: "Comisario General", value: "Comisario General"},

  ]
