export const tiposDeViolenciaText = [
  {tipo: "Física", text: "La que se emplea contra el cuerpo de la mujer produciendo dolor, daño o riesgo de producirlo y cualquier otra forma de maltrato agresión que afecte su integridad física."},
  {tipo: "Psicológica", text: "La que causa daño emocional y disminución de la autoestima o perjudica y perturba el pleno desarrollo personal o que busca degradar o controlar sus acciones, comportamientos, creencias y decisiones, mediante amenaza, acoso, hostigamiento, restricción, humillación, deshonra, descrédito, manipulación aislamiento. Incluye también la culpabilización, vigilancia constante, exigencia de obediencia sumisión, coerción verbal, persecución, insulto, indiferencia, abandono, celos excesivos, chantaje, ridiculización, explotación y limitación del derecho de circulación o cualquier otro medio que cause perjuicio a su salud psicológica y a la autodeterminación."},
  {tipo: "Sexual", text: "Cualquier acción que implique la vulneración en todas sus formas, con o sin acceso genital, del derecho de la mujer de decidir voluntariamente acerca de su vida sexual o reproductiva a través de amenazas, coerción, uso de la fuerza o intimidación, incluyendo la violación dentro del matrimonio o de otras relaciones vinculares o de parentesco, exista o no convivencia, así como la prostitución forzada, explotación, esclavitud, acoso, abuso sexual y trata de mujeres."},
  {tipo: "Económica y patrimonial", text:"La que se dirige a ocasionar un menoscabo en los recursos económicos o patrimoniales de la mujer, a través de:", subtext: 
    ["a) La perturbación de la posesión, tenencia o propiedad de sus bienes;", "b) La pérdida, sustracción, destrucción, retención o distracción indebida de objetos, instrumentos de trabajo, documentos personales, bienes, valores y derechos patrimoniales;", "c) La limitación de los recursos económicos destinados a satisfacer sus necesidades o privación de los medios indispensables para vivir una vida digna;", "d) La limitación o control de sus ingresos, así como la percepción de un salario menor por igual tarea, dentro de un mismo lugar de trabajo."]
  },
  {tipo: "Simbólica", text: "La que a través de patrones estereotipados, mensajes, valores, íconos o signos transmita y reproduzca dominación, desigualdad y discriminación en las relaciones sociales, naturalizando la subordinación de la mujer en la sociedad."},
  {tipo: "Política", text: "La que se dirige a menoscabar, anular, impedir, obstaculizar o restringir la participación política de la mujer, vulnerando el derecho a una vida política libre de violencia y/o el derecho a participar en los asuntos públicos y políticos en condiciones de igualdad con los varones. (Inciso incorporado por art. 3° de la Ley N° 27.533 B.O. 20/12/2019)"}
] 

export const tiposModalidades = [
  {tipo: "Violencia doméstica contra las mujeres", text: " Aquella ejercida contra las mujeres por un integrante del grupo familiar, independientemente del espacio físico donde ésta ocurra, que dañe la dignidad, el bienestar, la integridad física, psicológica, sexual, económica o patrimonial, la libertad, comprendiendo la libertad reproductiva y el derecho al pleno desarrollo de las mujeres. Se entiende por grupo familiar el originado en el parentesco sea por consanguinidad o por afinidad, el matrimonio, las uniones de hecho y las parejas o noviazgos. Incluye las relaciones vigentes o finalizadas, no siendo requisito la convivencia;"},
  {tipo: "Violencia institucional contra las mujeres", text: "Aquella realizada por las/los funcionarias/os, profesionales, personal y agentes pertenecientes a cualquier órgano, ente o institución pública, que tenga como fin retardar, obstaculizar o impedir que las mujeres tengan acceso a las políticas públicas y ejerzan los derechos previstos en esta ley. Quedan comprendidas, además, las que se ejercen en los partidos políticos, sindicatos, organizaciones empresariales, deportivas y de la sociedad civil;"},
  {tipo: " Violencia laboral contra las mujeres", text: "Aquella que discrimina a las mujeres en los ámbitos de trabajo públicos o privados y que obstaculiza su acceso al empleo, contratación, ascenso, estabilidad o permanencia en el mismo, exigiendo requisitos sobre estado civil, maternidad, edad, apariencia física o la realización de test de embarazo. Constituye también violencia contra las mujeres en el ámbito laboral quebrantar el derecho de igual remuneración por igual tarea o función. Asimismo, incluye el hostigamiento psicológico en forma sistemática sobre una determinada trabajadora con el fin de lograr su exclusión laboral;"},
  {tipo: "Violencia contra la libertad reproductiva", text: "Aquella que vulnere el derecho de las mujeres a decidir libre y responsablemente el número de embarazos o el intervalo entre los nacimientos, de conformidad con la Ley 25.673 de Creación del Programa Nacional de Salud Sexual y Procreación Responsable;"},
  {tipo: "Violencia obstétrica", text: "Aquella que ejerce el personal de salud sobre el cuerpo y los procesos reproductivos de las mujeres, expresada en un trato deshumanizado, un abuso de medicalización y patologización de los procesos naturales, de conformidad con la Ley 25.929."},
  {tipo: "Violencia mediática contra las mujeres", text: "Aquella publicación o difusión de mensajes e imágenes estereotipados a través de cualquier medio masivo de comunicación, que de manera directa o indirecta promueva la explotación de mujeres o sus imágenes, injurie, difame, discrimine, deshonre, humille o atente contra la dignidad de las mujeres, como así también la utilización de mujeres, adolescentes y niñas en mensajes e imágenes pornográficas, legitimando la desigualdad de trato o construya patrones socioculturales reproductores de la desigualdad o generadores de violencia contra las mujeres."},
  {tipo: "Violencia contra las mujeres en el espacio público", text: " aquella ejercida contra las mujeres por una o más personas, en lugares públicos o de acceso público, como medios de transporte o centros comerciales, a través de conductas o expresiones verbales o no verbales, con connotación sexual, que afecten o dañen su dignidad, integridad, libertad, libre circulación o permanencia y/o generen un ambiente hostil u ofensivo. (Inciso incorporado por art. 1° de la Ley N° 27.501 B.O. 8/5/2019)"},
  {tipo: "Violencia pública-política contra las mujeres" , text: "Aquella que, fundada en razones de género, mediando intimidación, hostigamiento, deshonra, descrédito, persecución, acoso y/o amenazas, impida o limite el desarrollo propio de la vida política o el acceso a derechos y deberes políticos, atentando contra la normativa vigente en materia de representación política de las mujeres, y/o desalentando o menoscabando el ejercicio político o la actividad política de las mujeres, pudiendo ocurrir en cualquier espacio de la vida pública y política, tales como instituciones estatales, recintos de votación, partidos políticos, organizaciones sociales, asociaciones sindicales, medios de comunicación, entre otros. (Inciso incorporado por art. 4° de la Ley N° 27.533 B.O. 20/12/2019)"},
  {tipo: "Violencia digital o telemática", text: "Toda conducta, acción u omisión en contra de las mujeres basada en su género que sea cometida, instigada o agravada, en parte o en su totalidad, con la asistencia, utilización y/o apropiación de las tecnologías de la información y la comunicación, con el objeto de causar daños físicos, psicológicos, económicos, sexuales o morales tanto en el ámbito privado como en el público a ellas o su grupo familiar. En especial conductas que atenten contra su integridad, dignidad, identidad, reputación, libertad, y contra el acceso, permanencia y desenvolvimiento en el espacio digital o que impliquen la obtención, reproducción y difusión, sin consentimiento de material digital real o editado, intimo o de desnudez, que se le atribuya a las mujeres, o la reproducción en el espacio digital de discursos de odio misóginos y patrones estereotipados sexistas o situaciones de acoso, amenaza, extorsión, control o espionaje de la actividad virtual, accesos no autorizados a dispositivos electrónicos o cuentas en línea, robo y difusión no consentida de datos personales en la medida en que no sean conductas permitidas por la ley 25.326 y/o la que en el futuro la reemplace, o acciones que atenten contra la integridad sexual de las mujeres a través de las tecnologías de la información y la comunicación, o cualquier ciberataque que pueda surgir a futuro y que afecte los derechos protegidos en la presente ley."}
]