export const ocupaciones = [
    // Empleado, Jornalero, Personal de Salud, Personal de educación, Profesional, Jubilado, Estudiante, Albañil, Policia, PFA, SPP, SPF, PSA, GNA, Ejército Argentina, PNA, Desocupado, Ama de casa, Empleado público, Comerciante, 
    { nombre: 'Ama de casa', value: 'Ama de casa' },
    { nombre: 'Empleado', value: 'Empleado' },
    { nombre: 'Empleado público', value: 'Empleado público' },
    { nombre: 'Jornalero', value: 'Jornalero' },
    {nombre: 'Independiente', value: 'Independiente'},
    { nombre: 'Comerciante', value: 'Comerciante' },
    { nombre: 'Personal de Salud', value: 'Personal de Salud' },
    { nombre: 'Personal de educación', value: 'Personal de educación' },
    { nombre: 'Profesional', value: 'Profesional' },
    { nombre: 'Jubilado', value: 'Jubilado' },
    { nombre: 'Estudiante', value: 'Estudiante' },
    { nombre: 'Albañil', value: 'Albañil' },
    { nombre: 'Policía Provincial', value: 'Policía Provincial' },
    { nombre: 'Policía Federal Argentina', value: 'Policía Federal Argentina' },
    { nombre: 'Servicio Penitenciario Provincial', value: 'Servicio Penitenciario Provincial' },
    { nombre: 'Servicio Penitenciario Federal', value: 'Servicio Penitenciario Federal' },
    { nombre: 'Policía de Seguridad Aeroportuaria', value: 'Policía de Seguridad Aeroportuaria' },
    { nombre: 'Gendarmería Nacional Argentina', value: 'Gendarmería Nacional Argentina' },
    { nombre: 'Ejército Argentino', value: 'Ejército Argentino' },
    { nombre: 'Prefectura Naval Argentina', value: 'Prefectura Naval Argentina' },
    { nombre: 'Desocupado', value: 'Desocupado' },
]